frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "app/(shop)/**"
          - "components/**"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "app/api/**"

admin:
  - changed-files:
      - any-glob-to-any-file:
          - "app/(admin)/**"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "next.config.ts"
          - "package.json"
          - "tsconfig.json"

database:
  - changed-files:
      - any-glob-to-any-file:
          - "supabase/**"
